# Generated by Django 6.0.2 on 2026-02-19 17:59

from django.db import migrations

import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.CustomUserManager()),
            ],
        ),
    ]
