# Generated by Django 6.0.2 on 2026-02-22 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        help_text="Укажите место, в котором необходимо выполнять привычку",
                        max_length=150,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time_habit",
                    models.TimeField(
                        help_text="Укажите время, когда необходимо выполнять привычку", verbose_name="Время"
                    ),
                ),
                (
                    "action_habit",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=250,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите признак приятной привычки",
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки для напоминания в днях",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Укажите время на выполнение привычки в секундах",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите признак публичности",
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя - создателя привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
