# Generated by Django 6.0.2 on 2026-02-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["time_habit"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
