# Generated by Django 6.0.2 on 2026-02-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя - создателя привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_reminder",
                    models.DateField(
                        blank=True, help_text="Укажите напоминания", null=True, verbose_name="Дата напоминания"
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя - создателя напоминания",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
