# Generated by Django 6.0.2 on 2026-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner_reminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={
                "ordering": ["date_reminder"],
                "verbose_name": "Напоминание",
                "verbose_name_plural": "Напоминания",
            },
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date_reminder",
            field=models.DateField(
                blank=True, help_text="Укажите дату напоминания", null=True, verbose_name="Дата напоминания"
            ),
        ),
    ]
